services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=bankdb
      - MYSQL_USER=${SQL_USERNAME}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: